Add missing dependency declarations to package manifest
swiftlang/swift-llbuild pull request #950
Opened 2024-11-06 02:49 UTC by ahoppen

This makes llbuild build with `swift build --explicit-target-dependency-import-check error`.

2024-11-06 02:49 UTC, ahoppen commented
@swift-ci Please test

2024-11-06 05:35 UTC, dmbryson approved these changes

2024-11-06 17:35 UTC, ahoppen commented
@swift-ci Please test Windows

2024-11-06 17:35 UTC, ahoppen commented
@swift-ci Please test Linux

2024-11-07 23:40 UTC, ahoppen commented
@swift-ci Please smoke test

2024-11-12 01:06 UTC, ahoppen commented
@swift-ci Please test Windows

2024-11-12 01:07 UTC, ahoppen commented
@swift-ci Please test

2024-11-12 04:04 UTC, owenv commented
SwiftPM is incorrectly flagging this as a missing dependency since it's unable to parse clang module maps to determine those module names with 100% accuracy. https://github.com/swiftlang/swift-llbuild/pull/891 and linked PRs have some context where this change broke builds last time it was made

2024-11-12 04:05 UTC, owenv requested changes
Please see above before merging (sorry, I posted it as a comment instead of review)

2024-11-12 16:18 UTC, ahoppen commented
Is there an issue tracking this incorrectly flagged issue on the SwiftPM side?

2024-11-13 23:01 UTC, closed without merging